name: Build-Docker

on:
  push:
    branches:
    - 'master'
    paths:
    - basic-auth/**

jobs:
  release_job:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'basic-auth/Dockerfile'
      context: './basic-auth'
      imageName: 'baoduy2412/squid-basic-auth'
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
