name: Build-Docker

on:
  push:
    branches:
    - 'master'
    paths:
    - basic-auth/**
  schedule:
    # Runs at 00:00, on day 1 of the month, every 3 months.
    - cron: '0 0 1 */3 *'

jobs:
  docker_job:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'basic-auth/Dockerfile'
      context: './basic-auth'
      imageName: 'baoduy2412/squid-basic-auth'
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  github_job:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'basic-auth/Dockerfile'
      context: './basic-auth'
      imageName: ghcr.io/${{ github.repository }}
      platforms: linux/arm64,linux/amd64
      DOCKER_REGISTRY: ghcr.io
    secrets:
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
